# Generated by Django 2.0.3 on 2018-03-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('imdb_url', models.URLField(max_length=128)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('season', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
